[package]
name = "yasc-ssh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
russh = { version = "0.62.5", default-features = false, features = ["ring", "rsa"] }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
yasc-domain.workspace = true
yasc-vault.workspace = true

[dev-dependencies]
futures = "0.3"
rand = "0.10"

[lints]
workspace = true
